#!/usr/bin/env ansible-playbook
---
- name: Corosync Key generation
  hosts: drbd-cluster

  tasks:
  - stat: 
      path: /etc/corosync/authkey
    register: corosync_authkey
    when: ansible_hostname == "virt-cl-drbd-0"

  - name: Create /etc/corosync files
    template: 
      src: ../templates/corosync/{{ item }}.j2
      dest: /etc/corosync/{{ item }}
    with_items:
      - corosync.conf
      - cluster_stack.crm
      - cluster_stack_clvm.crm
      - vm_stack.crm

  - name: Corosync key generation on node 0
    command: 'corosync-keygen -l'
    when: 
      - ansible_hostname == "virt-cl-drbd-0"
      - corosync_authkey.stat.exists == false

  - name: Corosync copy /etc/corosync/authkey 
    synchronize:
      src: /etc/corosync/authkey
      dest: /etc/corosync/authkey
      rsync_opts:
        - "-e ssh"
    when: ansible_hostname == "virt-cl-drbd-1"

  - name: Create a directory /etc/corosync/service.d
    file:
      path: /etc/corosync/service.d
      state: directory
      
  - name: Create /etc/corosync/service.d/pcmk
    template:
      src: ../templates/corosync/pcmk.j2
      dest: /etc/corosync/service.d/pcmk
