#!/usr/bin/env ansible-playbook
---
- name: Configuration of git username and email.
  hosts: all
  any_errors_fatal: true
  tasks:

  - name: apt Install git
    apt: 'name={{item}} state=present update_cache=yes'
    with_items:
      - "git"
    when: ansible_os_family == "Debian"

  - name: yum Install git
    yum: 'name={{item}} state=present update_cache=yes'
    with_items:
      - "git"
    when: ansible_os_family == "RedHat"

  - name: Adding git username
    git_config:
      name: user.name
      scope: global
      value: "Peter Pouliot"

  - name: Adding git email
    git_config:
      name: user.email
      scope: global
      value: "peter@pouliot.net"
