#!/usr/bin/env ansible-playbook
---
- name: Configuration of default network for libvirt as br0
  hosts: drbd-cluster
  any_errors_fatal: true
  tasks:

  - name: Creating /etc/libvirt/libvirt.conf
    template:
      src: ../templates/libvirt/libvirt.conf.j2
      dest: /etc/libvirt/libvirt.conf

  - name: Stop and Disable Libvirtd for control via Cluster Stack
    service:
      name: libvirtd
      enabled: false
      state: stopped

  - stat:
      path: /etc/libvirt/qemu/
    register: has_qemu

  - stat:
      path: /etc/libvirt/qemu/lost+found
    register: has_ocfs_mounted

  - stat:
      path: /etc/libvirt/qemu.default
    register: has_qemu_default

  - stat:
      path: /etc/libvirt/qemu/networks
    register: has_qemu_network


  - name: Creating /etc/libvirt/qemu.conf with ssl config on both hosts.
    template:
      src: ../templates/libvirt/qemu.conf.j2
      dest: /etc/libvirt/qemu.conf

  - name: moving default /etc/libvirt/qemu to /etc/libvirt/qemu.default
    command: mv /etc/libvirt/qemu /etc/libvirt/qemu.default
    when:
      - ansible_hostname == 'virt-cl-drbd-0'
      - has_qemu.stat.exists == 'true'
      - has_qemu_default.stat.exists == 'false'
      - has_ocfs_mounted.stat.exists == 'false'

  - name: Ensure directory /etc/libvirt/qemu/networks
    file:
      path: /etc/libvirt/qemu/networks
      state: directory
      mode: 0775
      owner: root
      group: root
    when:
      - ansible_hostname == 'virt-cl-drbd-0'
#      - has_qemu.stat.exists == 'true'
#      - has_qemu_default.stat.exists == 'true'
#      - has_qemu_network.stat.exists == 'false'
#      - has_ocfs_mounted.stat.exists == 'true'

  - name: Ensure directory /etc/libvirt/qemu/networks/autostart
    file:
      path: /etc/libvirt/qemu/networks/autostart
      state: directory
      mode: 0775
      owner: root
      group: root
    when:
      - ansible_hostname == 'virt-cl-drbd-0'
#      - has_qemu.stat.exists == 'true'
#      - has_qemu_default.stat.exists == 'true'
#      - has_qemu_network.stat.exists == 'false'
#      - has_ocfs_mounted.stat.exists == 'true'

  - name: Creating /etc/libvirt/qemu/networks/default.xml on one node because OCFS should be mounted
    template:
      src: ../templates/libvirt/default.xml.j2
      dest: /etc/libvirt/qemu/networks/default.xml
    when:
      - ansible_hostname == 'virt-cl-drbd-0'
#      - has_qemu.stat.exists == 'true'
#      - has_qemu_default.stat.exists == 'true'
#      - has_qemu_network.stat.exists == 'true'
#      - has_ocfs_mounted.stat.exists == 'true'
