#!/usr/bin/env ansible-playbook
---
- name: Required Cluster Packages
  hosts: drbd-cluster
  any_errors_fatal: true
  tasks:

  - name: Installing Munin Packages
    apt: 'name={{item}} state=present update_cache=yes'
    with_items:
      - "automake"
      - "autoconf"
      - "gcc"
      - "apache2-utils"
      - "nginx"
      - "spawn-fcgi"
      - "fcgiwrap"
      - "snmpd"
      - "sysstat"
      - "mrtg"
      - "libxml-simple-perl"
      - "libxml-twig-perl"
      - "munin-node"
      - "munin"
      - "munin-async"
      - "munin-plugins"
      - "munin-libvirt-plugins"
      - "munin-plugins-c"
      - "munin-plugins-core"
      - "munin-plugins-extra"
      - "munin-plugins-java"

  - name: Replacing /etc/snmpd.conf with one from template
    template:
      src: ../templates/snmpd.conf.j2
      dest: /etc/snmp/snmpd.conf
      owner: root
      group: root
      mode: "u=rw,g=r,o=r"

  - name: copying munin config templates
    template:
      src: ../templates/munin/{{ item }}.j2
      dest: /etc/munin/{{ item }}
      owner: root
      group: root
      mode: "u=rw,g=r,o=r"
    with_items:
      - munin.conf
      - munin-node.conf
      - plugin-conf.d/libvirt
      - plugin-conf.d/docker
      - plugin-conf.d/munin-node

  - name: munin-node service enabled/running
    service:
      name: munin-node
      enabled: true
      state: running

  - name: Replacing /etc/nginx/nginx.conf with one from template
    template:
      src: ../templates/nginx/nginx.default.j2
      dest: /etc/nginx/sites-available/default
      owner: root
      group: root
      mode: "u=rw,g=r,o=r"

  - name: Replacing /etc/init.d/munin-fastcgi with one from template
    template:
      src: ../templates/nginx/munin-fastcgi.j2
      dest: /etc/init.d/munin-fastcgi
      owner: root
      group: root
      mode: "0775"

  - name: Create symbolic link /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
    file:
      src: /etc/nginx/sites-available/default
      dest: /etc/nginx/sites-enabled/default
      state: link

  - name: nginx service disable and stop because we are controlling this in the cluster stack with a virtual ip
    service:
      name: nginx
      enabled: false
      state: stopped

  - name: Installing Munin 3rd Party Plugins (https://github.com/munin-monitoring/contrib) from Github
    git:
      repo: https://github.com/munin-monitoring/contrib
      dest: /usr/share/munin/plugins-contrib
      clone: yes
      update: yes

  - name: Installing Munin 3rd Party Plugins (https://github.com/munin-monitoring/contrib) from Github
    git:
      repo: https://github.com/alaskacommunications/nagios_check_drbd9
      dest: /opt/nagios_check_drbd
      clone: yes
      update: yes

  - name: Create munin docker_cpu/memory
    file:
      src: /usr/share/munin/plugins-contrib/plugins/docker/{{ item }}
      dest: /usr/share/munin/plugins/docker_cpu
      state: hard
    with_items:
      - docker_cpu
      - docker_memory
      
  - name: Create munin drbd
    file:
      src: /usr/share/munin/plugins-contrib/plugins/drbd/{{ item }}
      dest: /usr/share/munin/plugins/{{ item }}
      state: hard
    with_items:
      - drdb
      - drdb-stat

  - name: Create munin dell_fans
    file:
      src: /usr/share/munin/plugins-contrib/plugins/fan/dell_fans
      dest: /usr/share/munin/plugins/dell_fans
      state: hard

  - name: Create munin libvert plugins
    file:
      src: /usr/share/munin/plugins-contrib/plugins/libvirt/{{ item }}
      dest: /usr/share/munin/plugins/{{ item }}
      state: hard
    with_items:
      - kvm_cpu
      - kvm_io
      - kvm_mem
      - kvm_net
      - munin-libvirtpy
 
  - name: Create symbolic links for munin plugins
    file:
      src: /usr/share/munin/plugins/{{ item }}
      dest: /etc/munin/plugins/{{ item }}
      state: link
    with_items:
      - docker_cpu
      - docker_memory
      - drdb
      - drdb-stat
      - dell_fans
      - kvm_cpu
      - kvm_io
      - kvm_mem
      - kvm_net
      - munin-libvirtpy

#  - name: Create munin libvirt
#    file:
#      src: /usr/share/munin/plugins-contrib/plugins/libvirt/libvirt
#      dest: /usr/share/munin/plugins/libvirt
#      state: hard

#  - name: Create symbolic link for munin libvirt
#    file:
#      src: /usr/share/munin/plugins/libvirt
#      dest: /etc/munin/plugins/libvirt
#      state: link

  - name: Set Munin/munin 0755  File Permissions
    file:
      path: /etc/munin/plugin-conf.d
      state: directory
      mode: 0755
      owner: munin
      group: munin
      recurse: yes
    with_items:
      - /etc/munin/plugin-conf.d
      - /var/lib/munin
      - /var/log/munin

  - name: Set Munin /var/lib/munin/cgi-tmp File Permissions
    file:
      path: /var/lib/munin/cgi-tmp
      state: directory
      mode: 0644
      owner: munin
      group: www-data
      recurse: yes

  - name: Set Munin /var/lib/munin-node/plugin-state File Permissions
    file:
      path: /var/lib/munin-node/plugin-state
      state: directory
      mode: 0775
      owner: nobody
      group: nogroup
      recurse: yes

  - name: Ensure Munin directory /var/cache/munin/www
    file:
      path: /var/cache/munin/www
      state: directory
      mode: 0775
      owner: munin
      group: www-data
      recurse: yes

