#!/usr/bin/env ansible-playbook
---
- name: OCFS2 resources
  hosts: drbd-cluster

  tasks:
  - name: Create /etc/ocfs2/cluster.conf
    template: 
      src: ../templates/ocfs2/ocfs2_cluster.conf.j2
      dest: /etc/ocfs2/cluster.conf
