#!/usr/bin/env ansible-playbook
---
- name: DRDB /etc/hosts
  hosts: drbd-cluster
  any_errors_fatal: true

  tasks:
  - name: DRDB /etc/hosts
    template:
      src: ../templates/hosts.j2
      dest: /etc/hosts
      owner: root
      mode: 0644

  - name: DRDB /etc/netplan/01-netcfg.yml on node 0
    template: 
      src: ../templates/netplan/01-netcfg.yaml.j2
      dest: /etc/netplan/01-netcfg.yaml
      owner: root
    when: ansible_hostname == "virt-cl-drbd-0" or ansible_hostname == "virt-cl-drbd-1"
      
  - name: Ensure SSH Auth keys
    authorized_key: 
        user: root
        state: present
        key: "{{ lookup('file', '../keys/id_rsa.pub') }}"

  - name: copy misc scripts from /etc/ansible/bin to /root/bin
    synchronize:
      src: /etc/ansible/files/bin 
      dest: /root/
      rsync_opts:
        - "-e ssh"
    when: ansible_hostname == "virt-cl-drbd-0" or ansible_hostname == "virt-cl-drbd-1"
